---
title: "Assignment"
description: |
  This assignment is aim to solve the problems of for Mini Challenge 2
author:
  - name: LI NAN
    url: https://www.linkedin.com/in/li-nan-63b9251a6/
date: 07-12-2021
output:
  distill::distill_article:
    toc: true
    toc_depth: 3



---

## 1.Data Preparation

### 1.1 Global Settings

The global settings of R code chunks in this post is set as follows. 

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.retina = 3,
                      echo = TRUE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

### 1.2 R Packages Installation

The following code input is to prepare for R Packages Installation.

```{r}
packages = c('DT', 'ggiraph', 'plotly', 'tidyverse','dplyr','readr')
for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}

```

### 1.3 Data Import
The following code is to import raw data sets from [<font size="3"  color="blue">*Mini Challenge2*</font>](https://vast-challenge.github.io/2021/MC2.html)("*car-assignment.csv*","*cc_data.csv*","*gps.csv*","*loyalty_data.csv*").

```{r}
credit_debit <- read_csv("data/cc_data.csv")
loyalty_data <- read_csv("data/loyalty_data.csv")
car_assignment <- read_csv("data/car_assignments.csv")
GPS <- read_csv("data/gps.csv")
glimpse(credit_debit)

```

